import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import Header from "@/components/header";
import SideBar from "@/components/sideBar";
import Container from "@/components/container";

const fontSans = FontSans({ 
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex",
          fontSans.variable
        )}
      >
        <SideBar />
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
